#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pep8
Version  : 1.7.0
Release  : 22
URL      : http://pypi.debian.net/pep8/pep8-1.7.0.tar.gz
Source0  : http://pypi.debian.net/pep8/pep8-1.7.0.tar.gz
Summary  : Python style guide checker
Group    : Development/Tools
License  : MIT
Requires: pep8-bin
Requires: pep8-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
pep8 - Python style guide checker
=================================
pep8 is a tool to check your Python code against some of the style
conventions in `PEP 8`_.

%package bin
Summary: bin components for the pep8 package.
Group: Binaries

%description bin
bin components for the pep8 package.


%package python
Summary: python components for the pep8 package.
Group: Default

%description python
python components for the pep8 package.


%prep
%setup -q -n pep8-1.7.0

%build
export LANG=C
export SOURCE_DATE_EPOCH=1484561791
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python2.7/site-packages python2 setup.py test
%install
export SOURCE_DATE_EPOCH=1484561791
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pep8

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
